// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace UsedCarsPricePrediction_Train
{
    public partial class UsedCarsPricePredictionMLModel
    {
        /// <summary>
        /// model input class for UsedCarsPricePredictionMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Location")]
            public string Location { get; set; }

            [ColumnName(@"Year")]
            public float Year { get; set; }

            [ColumnName(@"Kilometers_Driven")]
            public float Kilometers_Driven { get; set; }

            [ColumnName(@"Fuel_Type")]
            public string Fuel_Type { get; set; }

            [ColumnName(@"Transmission")]
            public string Transmission { get; set; }

            [ColumnName(@"Owner_Type")]
            public string Owner_Type { get; set; }

            [ColumnName(@"Engine")]
            public string Engine { get; set; }

            [ColumnName(@"Power")]
            public string Power { get; set; }

            [ColumnName(@"Seats")]
            public float Seats { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for UsedCarsPricePredictionMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("UsedCarsPricePredictionMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
