// <auto-generated />
using CoreWebsite.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreWebsite.EntityFramework.Migrations
{
    [DbContext(typeof(WebsiteDbContext))]
    [Migration("20180815055859_add_Class")]
    partial class add_Class
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.ActivityComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ActivityId");

                    b.Property<string>("Content");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityComments");
                });

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.EntityRelationTest.AdmissionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AdmissionTime");

                    b.Property<string>("Remark");

                    b.HasKey("Id");

                    b.ToTable("AdmissionRecords");
                });

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.EntityRelationTest.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassName");

                    b.Property<DateTime>("CreationTime");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.EntityRelationTest.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AdmissionRecordId");

                    b.Property<long>("ClassId");

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionRecordId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.ActivityComment", b =>
                {
                    b.HasOne("CoreWebsite.EntityFramework.Models.Activity", "Activity")
                        .WithMany("ActivityComments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreWebsite.EntityFramework.Models.EntityRelationTest.Student", b =>
                {
                    b.HasOne("CoreWebsite.EntityFramework.Models.EntityRelationTest.AdmissionRecord", "AdmissionRecord")
                        .WithMany()
                        .HasForeignKey("AdmissionRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoreWebsite.EntityFramework.Models.EntityRelationTest.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");
                });
#pragma warning restore 612, 618
        }
    }
}
