﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace OrderStatusPrediction_Train
{
    public partial class OrderStatusPredictionMLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"cod", @"cod")      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"quantity", @"quantity"),new InputOutputColumnPair(@"item_total", @"item_total"),new InputOutputColumnPair(@"shipping_fee", @"shipping_fee")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"order_no", @"order_no"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"order_date", @"order_date"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"buyer", @"buyer"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"ship_city", @"ship_city"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"ship_state", @"ship_state"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"sku", @"sku"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"description", @"description"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"cod",@"quantity",@"item_total",@"shipping_fee",@"order_no",@"order_date",@"buyer",@"ship_city",@"ship_state",@"sku",@"description"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"order_status", @"order_status"))
                                    //引用Microsoft.ML.FastTree
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=6,FeatureFraction=1F,LabelColumnName=@"order_status",FeatureColumnName=@"Features"}), labelColumnName: @"order_status"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
