// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace OrderStatusPrediction_Train
{
    public partial class OrderStatusPredictionMLModel
    {
        /// <summary>
        /// model input class for OrderStatusPredictionMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"order_no")]
            public string Order_no { get; set; }

            [ColumnName(@"order_date")]
            public string Order_date { get; set; }

            [ColumnName(@"buyer")]
            public string Buyer { get; set; }

            [ColumnName(@"ship_city")]
            public string Ship_city { get; set; }

            [ColumnName(@"ship_state")]
            public string Ship_state { get; set; }

            [ColumnName(@"sku")]
            public string Sku { get; set; }

            [ColumnName(@"description")]
            public string Description { get; set; }

            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"item_total")]
            public string Item_total { get; set; }

            [ColumnName(@"shipping_fee")]
            public string Shipping_fee { get; set; }

            [ColumnName(@"cod")]
            public string Cod { get; set; }

            [ColumnName(@"order_status")]
            public string Order_status { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for OrderStatusPredictionMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("OrderStatusPredictionMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
