﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace OrderStatusPrediction_Train
{
    public partial class OrderStatusPredictionMLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(@"quantity", @"quantity")      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"order_no", @"order_no"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"order_date", @"order_date"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"buyer", @"buyer"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"ship_city", @"ship_city"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"ship_state", @"ship_state"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"sku", @"sku"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"description", @"description"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"item_total", @"item_total"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"shipping_fee", @"shipping_fee"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"cod", @"cod"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"quantity",@"order_no",@"order_date",@"buyer",@"ship_city",@"ship_state",@"sku",@"description",@"item_total",@"shipping_fee",@"cod"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"order_status", @"order_status"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(l1Regularization:2.96438663080104F,l2Regularization:5.11307133813311F,labelColumnName:@"order_status",featureColumnName:@"Features"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
